Lisp: LFunctionL Class Reference
LFunctionL Class Reference
Lispovská funkce.
#include <datetypes.h>
Public Member Functions
LFunctionL ()
LFunctionL (LList *params, LList *funct)
virtual string printable ()
virtual string whois ()
virtual Elem * copy ()
Vrátí kopii objektu.
Elem * call (LList *params, Enviroment *env)
Public Attributes
LList * params
seznam parametrů
LList * funct
seznam reprezentující tělo funkce
Detailed Description
Lispovská funkce.
Definition at line 169 of file datetypes.h.
Constructor & Destructor Documentation
LFunctionL::LFunctionL () [inline]
Definition at line 172 of file datetypes.h.
LFunctionL::LFunctionL (LList * params, LList * funct) [inline]
Definition at line 175 of file datetypes.h.
Member Function Documentation
string LFunctionL::printable () [virtual]
Vrátí tisknutelnou reprezentaci Elem. Je používáno při debuggingu a funkcí print
Implements Elem.
Definition at line 222 of file datetypes.cpp.
string LFunctionL::whois () [virtual]
funkce whois() vrátí textový identifikátor datového typu. Používá se kvůli dynamickému typování lispu
Implements Elem.
Definition at line 228 of file datetypes.cpp.
Elem * LFunctionL::copy () [virtual]
Vrátí kopii objektu.
Implements Elem.
Definition at line 232 of file datetypes.cpp.
References LList::copy(), funct, and params.
Elem * LFunctionL::call (LList * params, Enviroment * env) [virtual]
Implements LFunction.
Definition at line 241 of file datetypes.cpp.
References LList::car, LList::cdr, Enviroment::define(), BaseException::desc, funct, LList::len(), LSymbol::name, Enviroment::progn(), and strformat().
Member Data Documentation
LList* LFunctionL::params
seznam parametrů
Definition at line 188 of file datetypes.h.
Referenced by copy().
LList* LFunctionL::funct
seznam reprezentující tělo funkce
Definition at line 191 of file datetypes.h.
Referenced by call(), and copy().
The documentation for this class was generated from the following files:
datetypes.h
datetypes.cpp