Lisp: LFunctionC Class Reference
LFunctionC Class Reference
Primitivní funkce (v C).
#include <datetypes.h>
Public Member Functions
LFunctionC (Elem *(*funct)(LList *, Enviroment *env))
virtual string printable ()
virtual string whois ()
virtual Elem * copy ()
Vrátí kopii objektu.
Elem * call (LList *params, Enviroment *)
Public Attributes
Elem *(* funct)(LList *, Enviroment *)
Ukazatel na funkci v C (všecky mají stejné c-API).
Detailed Description
Primitivní funkce (v C).
Definition at line 149 of file datetypes.h.
Constructor & Destructor Documentation
LFunctionC::LFunctionC (Elem *(*)(LList *, Enviroment *env) funct) [inline]
Definition at line 152 of file datetypes.h.
References funct.
Referenced by copy().
Member Function Documentation
string LFunctionC::printable () [virtual]
Vrátí tisknutelnou reprezentaci Elem. Je používáno při debuggingu a funkcí print
Implements Elem.
Definition at line 195 of file datetypes.cpp.
string LFunctionC::whois () [virtual]
funkce whois() vrátí textový identifikátor datového typu. Používá se kvůli dynamickému typování lispu
Implements Elem.
Definition at line 203 of file datetypes.cpp.
Elem * LFunctionC::copy () [virtual]
Vrátí kopii objektu.
Implements Elem.
Definition at line 207 of file datetypes.cpp.
References LFunctionC().
Elem * LFunctionC::call (LList * params, Enviroment * env) [virtual]
Implements LFunction.
Definition at line 213 of file datetypes.cpp.
References funct.
Member Data Documentation
Elem*(* LFunctionC::funct)(LList *, Enviroment *)
Ukazatel na funkci v C (všecky mají stejné c-API).
Definition at line 164 of file datetypes.h.
Referenced by call(), and LFunctionC().
The documentation for this class was generated from the following files:
datetypes.h
datetypes.cpp