Lisp: Parser Class Reference
Parser Class Reference
Převede zdroják na programový strom.
#include <parser.h>
Public Member Functions
Parser ()
Inicializuje prázdný parser. Data k rozparsování se předávají metodama parseX().
LList * parseStream (istream &stream)
Převede předaný stream na string a předá parseString() (mají stejné API).
LList * parseString (string &s)
Private Member Functions
Elem * parseElem ()
Vezme další token a převede ho na Elem.
LList * n_List (string &tokRepr)
Vezme token typu LIST a převede ho na lispovský LList.
LInt * n_Int (string &tokRepr)
Vezme token typu INT a převede ho na token typu LInt.
LString * n_String (string &tokRepr)
Vezme token typu STRING a převede ho na token typu LString.
LSymbol * n_Symbol (string &tokRepr)
Vezme token typu SYMBOL a převede ho na token typu LSymbol.
Private Attributes
Tokenizer tokenizer
Detailed Description
Převede zdroják na programový strom.
Definition at line 14 of file parser.h.
Constructor & Destructor Documentation
Parser::Parser ()
Inicializuje prázdný parser. Data k rozparsování se předávají metodama parseX().
Definition at line 13 of file parser.cpp.
Member Function Documentation
LList * Parser::parseStream (istream & stream)
Převede předaný stream na string a předá parseString() (mají stejné API).
See also:
parseString()
Definition at line 16 of file parser.cpp.
References parseString().
Referenced by proccessFile().
LList * Parser::parseString (string & s)
Převede ředaný string na strom reprezentující program
Parameters:
s - textový řetěřec k rozparsování
Returns:
- strom reprezentující program
Definition at line 36 of file parser.cpp.
References n_List(), tokenizer, and Tokenizer::tokenizeString().
Referenced by parsec(), parseStream(), and Repl::run().
Elem * Parser::parseElem () [private]
Vezme další token a převede ho na Elem.
Definition at line 43 of file parser.cpp.
References INT, LIST_BEGIN, LIST_END, n_Int(), n_List(), n_String(), n_Symbol(), Tokenizer::nextToken(), STRING_BEGIN, SYMBOL, and tokenizer.
Referenced by n_List().
LList * Parser::n_List (string & tokRepr) [private]
Vezme token typu LIST a převede ho na lispovský LList.
Definition at line 88 of file parser.cpp.
References LList::add(), Tokenizer::col, Elem::col, Tokenizer::line, Elem::line, parseElem(), and tokenizer.
Referenced by parseElem(), and parseString().
LInt * Parser::n_Int (string & tokRepr) [private]
Vezme token typu INT a převede ho na token typu LInt.
Definition at line 101 of file parser.cpp.
References Tokenizer::col, Elem::col, Tokenizer::line, Elem::line, and tokenizer.
Referenced by parseElem().
LString * Parser::n_String (string & tokRepr) [private]
Vezme token typu STRING a převede ho na token typu LString.
Definition at line 109 of file parser.cpp.
References Tokenizer::col, Elem::col, Tokenizer::line, Elem::line, and tokenizer.
Referenced by parseElem().
LSymbol * Parser::n_Symbol (string & tokRepr) [private]
Vezme token typu SYMBOL a převede ho na token typu LSymbol.
Definition at line 117 of file parser.cpp.
References Tokenizer::col, Elem::col, Tokenizer::line, Elem::line, and tokenizer.
Referenced by parseElem().
Member Data Documentation
Tokenizer Parser::tokenizer [private]
Definition at line 29 of file parser.h.
Referenced by n_Int(), n_List(), n_String(), n_Symbol(), parseElem(), and parseString().
The documentation for this class was generated from the following files:
parser.h
parser.cpp