Lisp: Tokenizer Class Reference
Tokenizer Class Reference
Převedení zdrojáku na tokeny.
#include <tokenizer.h>
Public Member Functions
Tokenizer ()
Implicitní konstruktor vynuluje vnitřní proměnné.
void tokenizeString (string s)
token nextToken (string &tokRepr)
Public Attributes
int line
int col
Pozice v rámci řádku.
Private Member Functions
token nextToken2 (string &tokRepr)
void skipWhitespaces ()
Přesune ukazatel pozice na další kus kódu. Přeskakuje bílé znaky a komentáře (od # do konce rádku).
string readNum ()
Přečte a vrátí textovou reprezentaci čísla. Posune ukazatele pozice.
string readSymbol ()
Přečte a vrátí textovou reprezentaci symbolu. Posune ukazatele pozice.
string readText ()
Přečte a vrátí textovou reprezentaci lispovského stringu. Posune ukazatele pozice.
int getChar ()
Přečte a vrátí jeden znak. A posune všecky ukazatele pozice.
void ungetChar ()
Vrátí stav ukazatelů o jedno zavolání funkce getChar() zpět. Na konci zdrojáku vrátí -1.
Private Attributes
int pos
Pozice v aktuálně zpracovávaném řetězci (ukazuje na prvek ktery bude teprve cten).
string repr
interní reprezentace zpracovávaného řetězce
Detailed Description
Převedení zdrojáku na tokeny.
Třída Tokenizer slouží k "rozdrobení" zdrojáku na tokeny. Token je kousek zdrojáku s informací o jeho typu (např. "143" - INT). Zdroják se předává funkcí tokenizeString(), Tokeny se získávají fcí nextToken. Udržuje si informace v atributech line (zpracovávaný řádek) a col (pozice v řádku) (vhodné pro debugging)
Definition at line 22 of file tokenizer.h.
Constructor & Destructor Documentation
Tokenizer::Tokenizer () [inline]
Implicitní konstruktor vynuluje vnitřní proměnné.
Definition at line 25 of file tokenizer.h.
References col, line, and pos.
Member Function Documentation
void Tokenizer::tokenizeString (string s)
Konstruktor-like parametr který nastaví vnitřní stav objektu pro tokenizaci předaného stringu
Parameters:
s string který se bude tokenizovat
Definition at line 12 of file tokenizer.cpp.
References pos, and repr.
Referenced by Parser::parseString().
token Tokenizer::nextToken (string & tokRepr)
Funkce která se volá a která předává typ a textovou reprezentaci tokenu. Po posledním vrátí token 0
Parameters:
[out] tokRepr - sem se uloží textová reprezentace tokenu
Returns:
typ tokenu (definováno v tokendefs.h)
Definition at line 17 of file tokenizer.cpp.
References nextToken2().
Referenced by Parser::parseElem().
token Tokenizer::nextToken2 (string & tokRepr) [private]
skutečná funkce nextToken(). nextToken() jen předává práci této funkci (oddělené kvůli debuggingu). API je stejné jako nextToken()
Definition at line 23 of file tokenizer.cpp.
References DOUBLE, getChar(), INT, LIST_BEGIN, LIST_END, pos, readNum(), readSymbol(), readText(), repr, skipWhitespaces(), STRING_BEGIN, and SYMBOL.
Referenced by nextToken().
void Tokenizer::skipWhitespaces () [private]
Přesune ukazatel pozice na další kus kódu. Přeskakuje bílé znaky a komentáře (od # do konce rádku).
Definition at line 69 of file tokenizer.cpp.
References getChar(), pos, repr, and ungetChar().
Referenced by nextToken2().
string Tokenizer::readNum () [private]
Přečte a vrátí textovou reprezentaci čísla. Posune ukazatele pozice.
Definition at line 88 of file tokenizer.cpp.
References getChar(), and ungetChar().
Referenced by nextToken2().
string Tokenizer::readSymbol () [private]
Přečte a vrátí textovou reprezentaci symbolu. Posune ukazatele pozice.
Definition at line 108 of file tokenizer.cpp.
References getChar(), ischar(), and ungetChar().
Referenced by nextToken2().
string Tokenizer::readText () [private]
Přečte a vrátí textovou reprezentaci lispovského stringu. Posune ukazatele pozice.
Definition at line 119 of file tokenizer.cpp.
References col, BaseException::col, BaseException::desc, getChar(), line, and BaseException::line.
Referenced by nextToken2().
int Tokenizer::getChar () [private]
Přečte a vrátí jeden znak. A posune všecky ukazatele pozice.
Definition at line 139 of file tokenizer.cpp.
References col, line, pos, and repr.
Referenced by nextToken2(), readNum(), readSymbol(), readText(), and skipWhitespaces().
void Tokenizer::ungetChar () [private]
Vrátí stav ukazatelů o jedno zavolání funkce getChar() zpět. Na konci zdrojáku vrátí -1.
Definition at line 157 of file tokenizer.cpp.
References col, line, pos, and repr.
Referenced by readNum(), readSymbol(), and skipWhitespaces().
Member Data Documentation
int Tokenizer::line
Číslo řádku v zpracovávaném zdrojáku. Spolu s this->col se používá při chybových hlášeních
Definition at line 46 of file tokenizer.h.
Referenced by getChar(), Parser::n_Int(), Parser::n_List(), Parser::n_String(), Parser::n_Symbol(), readText(), Tokenizer(), and ungetChar().
int Tokenizer::col
Pozice v rámci řádku.
See also:
this->line.
Definition at line 48 of file tokenizer.h.
Referenced by getChar(), Parser::n_Int(), Parser::n_List(), Parser::n_String(), Parser::n_Symbol(), readText(), Tokenizer(), and ungetChar().
int Tokenizer::pos [private]
Pozice v aktuálně zpracovávaném řetězci (ukazuje na prvek ktery bude teprve cten).
Definition at line 74 of file tokenizer.h.
Referenced by getChar(), nextToken2(), skipWhitespaces(), Tokenizer(), tokenizeString(), and ungetChar().
string Tokenizer::repr [private]
interní reprezentace zpracovávaného řetězce
Definition at line 77 of file tokenizer.h.
Referenced by getChar(), nextToken2(), skipWhitespaces(), tokenizeString(), and ungetChar().
The documentation for this class was generated from the following files:
tokenizer.h
tokenizer.cpp