Lisp: LFunctionM Class Reference
LFunctionM Class Reference
Lispovské makro.
#include <datetypes.h>
Public Member Functions
LFunctionM ()
LFunctionM (LList *params, LList *funct)
virtual string printable ()
virtual string whois ()
virtual Elem * copy ()
Vrátí kopii objektu.
Elem * call (LList *params, Enviroment *env)
Public Attributes
LList * params
seznam parametrů
LList * funct
tělo makra
Detailed Description
Lispovské makro.
Definition at line 196 of file datetypes.h.
Constructor & Destructor Documentation
LFunctionM::LFunctionM () [inline]
Definition at line 199 of file datetypes.h.
LFunctionM::LFunctionM (LList * params, LList * funct) [inline]
Definition at line 202 of file datetypes.h.
Member Function Documentation
string LFunctionM::printable () [virtual]
Vrátí tisknutelnou reprezentaci Elem. Je používáno při debuggingu a funkcí print
Implements Elem.
Definition at line 267 of file datetypes.cpp.
References funct, and LList::printable().
string LFunctionM::whois () [virtual]
funkce whois() vrátí textový identifikátor datového typu. Používá se kvůli dynamickému typování lispu
Implements Elem.
Definition at line 274 of file datetypes.cpp.
Elem * LFunctionM::copy () [virtual]
Vrátí kopii objektu.
Implements Elem.
Definition at line 278 of file datetypes.cpp.
References LList::copy(), funct, and params.
Elem * LFunctionM::call (LList * params, Enviroment * env) [virtual]
Implements LFunction.
Definition at line 287 of file datetypes.cpp.
References LList::car, LList::cdr, LList::copy(), Enviroment::define(), BaseException::desc, Enviroment::eval(), funct, LList::len(), LSymbol::name, Enviroment::progn(), and strformat().
Member Data Documentation
LList* LFunctionM::params
seznam parametrů
Definition at line 215 of file datetypes.h.
Referenced by copy().
LList* LFunctionM::funct
tělo makra
Definition at line 218 of file datetypes.h.
Referenced by call(), copy(), and printable().
The documentation for this class was generated from the following files:
datetypes.h
datetypes.cpp