Lisp: Repl Class Reference
Repl Class Reference
Repl - interaktivní interpret lispu.
#include <repl.h>
Public Member Functions
void run (Enviroment env)
Private Member Functions
string getline (istream &is)
načte a vrátí řádek načtený z parametru is
Detailed Description
Repl - interaktivní interpret lispu.
Definition at line 26 of file repl.h.
Member Function Documentation
void Repl::run (Enviroment env)
Spustí REPL
Parameters:
env - enviroment ve kterém REPL poběží
Definition at line 11 of file repl.cpp.
References evalProgram(), getline(), and Parser::parseString().
Referenced by main(), and replc().
string Repl::getline (istream & is) [private]
načte a vrátí řádek načtený z parametru is
Definition at line 24 of file repl.cpp.
Referenced by run().
The documentation for this class was generated from the following files:
repl.h
repl.cpp