Lisp: Elem Class Reference
Elem Class Reference
Abstraktní prataťka všech datových typů.
#include <datetypes.h>
Public Member Functions
Elem ()
virtual string printable ()=0
virtual string whois ()=0
virtual Elem * copy ()=0
Vrátí kopii objektu.
Public Attributes
int line
Číslo řádku (kvůli zobrazuje se v chybových hláškách).
int col
Pozice na řádku.
Detailed Description
Abstraktní prataťka všech datových typů.
Definition at line 15 of file datetypes.h.
Constructor & Destructor Documentation
Elem::Elem () [inline]
Definition at line 18 of file datetypes.h.
References col, and line.
Member Function Documentation
virtual string Elem::printable () [pure virtual]
Vrátí tisknutelnou reprezentaci Elem. Je používáno při debuggingu a funkcí print
Implemented in LSymbol, LInt, LList, LString, LFunctionC, LFunctionL, LFunctionM, and LBool.
Referenced by evalc(), LList::printable(), printc(), and Enviroment::vardump().
virtual string Elem::whois () [pure virtual]
funkce whois() vrátí textový identifikátor datového typu. Používá se kvůli dynamickému typování lispu
Implemented in LSymbol, LInt, LList, LString, LFunctionC, LFunctionL, LFunctionM, and LBool.
Referenced by backquotec(), equalc(), Enviroment::eval(), expect_X(), lequeal(), and setc().
virtual Elem* Elem::copy () [pure virtual]
Vrátí kopii objektu.
Implemented in LSymbol, LInt, LList, LString, LFunctionC, LFunctionL, LFunctionM, and LBool.
Referenced by LList::copy().
Member Data Documentation
int Elem::line
Číslo řádku (kvůli zobrazuje se v chybových hláškách).
Definition at line 35 of file datetypes.h.
Referenced by Elem(), Enviroment::eval(), lambdac(), lequeal(), Parser::n_Int(), Parser::n_List(), Parser::n_String(), and Parser::n_Symbol().
int Elem::col
Pozice na řádku.
See also:
this->line
Definition at line 37 of file datetypes.h.
Referenced by Elem(), lambdac(), Parser::n_Int(), Parser::n_List(), Parser::n_String(), and Parser::n_Symbol().
The documentation for this class was generated from the following file:
datetypes.h