Lisp: Enviroment Class Reference
Enviroment Class Reference
Enviroment - prostředí ve kterém se provádí kód.
#include <enviroment.h>
Public Member Functions
Enviroment ()
Implicitní konstuktor - vytvoří prázdný enviroment a definuje primitivní symboly.
Enviroment (Enviroment &)
Korektně fungující kopírující konstruktor.
void define (string name, Elem *val)
definuje symbol (proměnou)
void vardump ()
Vypíše všecky definované symboly v aktuálním enviromentu.
LList * evalAll (LList *expr)
Elem * eval (Elem *expr)
Elem * progn (LList *expr)
Public Attributes
map< string, Elem * > symbols
Tabulka definovaných symbolů.
Enviroment * parent
Odkaz na nadřazený enviroment (kvůli fci exportall).
Detailed Description
Enviroment - prostředí ve kterém se provádí kód.
Definition at line 19 of file enviroment.h.
Constructor & Destructor Documentation
Enviroment::Enviroment ()
Implicitní konstuktor - vytvoří prázdný enviroment a definuje primitivní symboly.
Definition at line 19 of file enviroment.cpp.
References andc(), backquotec(), biggerc(), carc(), cdrc(), consc(), defmacroc(), divisionc(), equalc(), evalc(), evallc(), exportallc(), ifc(), lambdac(), listc(), minusc(), moduloc(), multiplyc(), notc(), orc(), parent, parsec(), plusc(), printc(), prognc(), quotec(), readfilec(), replc(), setc(), smallerc(), symbols, and vardumpc().
Enviroment::Enviroment (Enviroment & r)
Korektně fungující kopírující konstruktor.
Definition at line 14 of file enviroment.cpp.
References parent, and symbols.
Member Function Documentation
void Enviroment::define (string name, Elem * val)
definuje symbol (proměnou)
Definition at line 58 of file enviroment.cpp.
References symbols.
Referenced by LFunctionM::call(), LFunctionL::call(), defmacroc(), exportallc(), and setc().
void Enviroment::vardump ()
Vypíše všecky definované symboly v aktuálním enviromentu.
Definition at line 62 of file enviroment.cpp.
References Elem::printable(), and symbols.
Referenced by vardumpc().
LList * Enviroment::evalAll (LList * expr)
evalAll - vyhodnotí parametry volání jen lispovské funkce (makra a primitivní funkce se evaluují jinak). Používá se kvůli call-by-value.
Parameters:
expr - parametry funkce
Returns:
nový seznam kde je každý prvek z expr evaluován
Definition at line 88 of file enviroment.cpp.
References LList::add(), LList::car, LList::cdr, and eval().
Referenced by eval().
Elem * Enviroment::eval (Elem * expr)
vyhodnotí seznam (+ 1 2) Pravidla vyhodnocování: int a string se vyhodnocují na sebe. symbol se vyhodnocuje na co představuje (pomocí tabulky symbolů this->symbols) U seznamu se předpokládá že to je volání funkce. Jestli je to lispovská funkce tak se evaluují parametry a funkce se zavolá. U primitivních funkcí (v C) a maker se parametry neevalují.
Definition at line 102 of file enviroment.cpp.
References BaseException::addFunction(), LFunction::call(), LList::car, LList::cdr, BaseException::desc, evalAll(), Elem::line, BaseException::line, LSymbol::name, symbols, and Elem::whois().
Referenced by andc(), backquotec(), biggerc(), LFunctionM::call(), carc(), cdrc(), consc(), divisionc(), equalc(), evalAll(), evalc(), ifc(), listc(), minusc(), moduloc(), multiplyc(), notc(), orc(), parsec(), plusc(), printc(), progn(), prognc(), readfilec(), setc(), and smallerc().
Elem * Enviroment::progn (LList * expr)
Vyhodnotí seznam seznamů ((+ 1 2) (* 5 6))
Returns:
hodnotu posledního výrazu
Definition at line 75 of file enviroment.cpp.
References LList::car, LList::cdr, and eval().
Referenced by LFunctionM::call(), LFunctionL::call(), evallc(), evalProgram(), and prognc().
Member Data Documentation
map<string, Elem *> Enviroment::symbols
Tabulka definovaných symbolů.
Definition at line 62 of file enviroment.h.
Referenced by define(), Enviroment(), eval(), exportallc(), and vardump().
Enviroment* Enviroment::parent
Odkaz na nadřazený enviroment (kvůli fci exportall).
Definition at line 65 of file enviroment.h.
Referenced by Enviroment(), and exportallc().
The documentation for this class was generated from the following files:
enviroment.h
enviroment.cpp