Lisp: datetypes.cpp File Reference
datetypes.cpp File Reference
#include <string>
#include <cstdio>
#include <iostream>
#include <sstream>
#include "datetypes.h"
#include <map>
#include "datetypes.h"
#include "enviroment.h"
#include <cstdarg>
#include <list>
#include "exceptions.h"
Functions
void Nparams (int n, LList *params)
template<typename T >
T * expect_X (Elem *x, string ident)
LBool * expect_LBool (Elem *x)
LInt * expect_LInt (Elem *x)
LList * expect_LList (Elem *x)
LString * expect_LString (Elem *x)
LSymbol * expect_LSymbol (Elem *x)
LFunctionC * expect_LfunctionC (Elem *x)
LFunctionL * expect_LfunctionL (Elem *x)
LFunctionM * expect_LfunctionM (Elem *x)
Function Documentation
void Nparams (int n, LList * params)
Pomocná funkce pro kontrolu počtu parametrů v primitivních funkcích.
Parameters:
n - požadovaný počet parametrů
params - parametry předané primitivní funkci
Returns:
- nic nevrací, v případě že počty parametrů sobě neoodpovídají, vyvolá vyjímku TypeException
Definition at line 356 of file datetypes.cpp.
References BaseException::desc, LList::len(), and strformat().
Referenced by defmacroc(), lambdac(), notc(), and setc().
template<typename T > T* expect_X (Elem * x, string ident) [inline]
šablona pro dynamickou kontrolu typů a přetypovávání
Parameters:
x - proměnná, jejíž typ se bude kontrolovat
ident - textový identifikátor požadovaného typu
Returns:
ukazatel na správný typ (místo obecného Elem*)
Definition at line 371 of file datetypes.cpp.
References BaseException::desc, strformat(), and Elem::whois().
LBool* expect_LBool (Elem * x)
Bere jako parametr ukazatel na obecný typ Elem, a v případě že jecíl ukazatele typu LBool tak vrátí přetypovaný ukazatel na tu hodnotu. Jinak vyhodí vyjímku TypeException
Parameters:
x - ukazatel na obecný typ Elem *
Returns:
- ukazatel na konkrétní typ LBool *
Definition at line 382 of file datetypes.cpp.
Referenced by andc(), ifc(), notc(), and orc().
LInt* expect_LInt (Elem * x)
See also:
expect_LBool
Definition at line 386 of file datetypes.cpp.
Referenced by biggerc(), divisionc(), lequeal(), minusc(), moduloc(), multiplyc(), plusc(), and smallerc().
LList* expect_LList (Elem * x)
See also:
expect_LBool
Definition at line 390 of file datetypes.cpp.
Referenced by backquotec(), carc(), cdrc(), defmacroc(), lambdac(), lequeal(), and prognc().
LString* expect_LString (Elem * x)
See also:
expect_LBool
Definition at line 394 of file datetypes.cpp.
Referenced by lequeal(), parsec(), and readfilec().
LSymbol* expect_LSymbol (Elem * x)
See also:
expect_LBool
Definition at line 398 of file datetypes.cpp.
Referenced by backquotec(), defmacroc(), and setc().
LFunctionC* expect_LfunctionC (Elem * x)
See also:
expect_LBool
Definition at line 406 of file datetypes.cpp.
LFunctionL* expect_LfunctionL (Elem * x)
See also:
expect_LBool
Definition at line 410 of file datetypes.cpp.
LFunctionM* expect_LfunctionM (Elem * x)
See also:
expect_LBool
Definition at line 414 of file datetypes.cpp.