Lisp: exceptions.cpp File Reference
exceptions.cpp File Reference
#include <string>
#include <cstring>
#include "exceptions.h"
Functions
string strformat (const char *format,...)
Function Documentation
string strformat (const char * format, ...)
vytvoří string z format-stringu (jako u printf) a libovolného množství parametrů které nesou hodnoty pro vložení. Example: strformat("čísla %d a %d jsou %s", a, b, a==b?"stejná":"různá")
Definition at line 6 of file exceptions.cpp.
Referenced by LFunctionM::call(), LFunctionL::call(), expect_X(), lequeal(), and Nparams().