Lisp: exceptions.h File Reference
exceptions.h File Reference
#include <string>
#include <cstdarg>
#include <cstdio>
#include <iostream>
#include <list>
#include "exceptions.h"
#include "datetypes.h"
Classes
class BaseException
Rodičovská, abstraktní třída všech vyjímek.
class IOException
vyjímka pro špatné I/O operace (neexistující soubor atd)
class NameException
vyjímka pro neexistující symbol (funkce i proměnné)
class SyntaxException
vyjímka pro chyby v syntaxi (vyhazuje Parser)
class TypeException
vyjímka pro špatně použité datové typy (počet a typ parametrů primitivních funkcí)
Functions
string strformat (const char *format,...)
Function Documentation
string strformat (const char * format, ...)
vytvoří string z format-stringu (jako u printf) a libovolného množství parametrů které nesou hodnoty pro vložení. Example: strformat("čísla %d a %d jsou %s", a, b, a==b?"stejná":"různá")
Definition at line 6 of file exceptions.cpp.
Referenced by LFunctionM::call(), LFunctionL::call(), expect_X(), lequeal(), and Nparams().