Lisp: repl.h File Reference
repl.h File Reference
#include <string>
#include <iostream>
#include "enviroment.h"
#include "exceptions.h"
#include "parser.h"
Classes
class Repl
Repl - interaktivní interpret lispu.
Functions
Elem * evalProgram (Enviroment *env, LList *program)
Elem * proccessFile (Enviroment &env, string filename)
Spustí lispovský program daný parametrem filename v enviromentu env.
Function Documentation
Elem* evalProgram (Enviroment * env, LList * program)
Spustí lispovský program předaný jako strom príkazů a zachytí a zobrazí user-friendly informace o případných chybách
Parameters:
env - enviroment ve kterém proběhne spuštění
program spuštěný program
Returns:
Buď návratovou hodnotu posledního příkazu nebo, v případě chyby, NULL
Definition at line 51 of file repl.cpp.
References BaseException::desc, BaseException::functions, BaseException::line, printTraceback(), and Enviroment::progn().
Referenced by proccessFile(), and Repl::run().
Elem* proccessFile (Enviroment & env, string filename)
Spustí lispovský program daný parametrem filename v enviromentu env.
Definition at line 74 of file repl.cpp.
References BaseException::desc, evalProgram(), BaseException::line, and Parser::parseStream().
Referenced by main().