Lisp: stdlibc.h File Reference
stdlibc.h File Reference
#include <stdio.h>
#include <iostream>
#include <fstream>
#include "datetypes.h"
#include "enviroment.h"
#include "parser.h"
#include "repl.h"
Functions
Elem * printc (LList *params, Enviroment *env)
Elem * setc (LList *params, Enviroment *env)
Elem * quotec (LList *params, Enviroment *env)
Elem * lambdac (LList *params, Enviroment *env)
Elem * defmacroc (LList *params, Enviroment *env)
Elem * listc (LList *params, Enviroment *env)
Elem * backquotec (LList *params, Enviroment *env)
Elem * ifc (LList *params, Enviroment *env)
Elem * evalc (LList *params, Enviroment *env)
Elem * evallc (LList *params, Enviroment *env)
Elem * prognc (LList *params, Enviroment *env)
Elem * carc (LList *params, Enviroment *env)
Elem * cdrc (LList *params, Enviroment *env)
Elem * parsec (LList *params, Enviroment *env)
Elem * readfilec (LList *params, Enviroment *env)
Elem * vardumpc (LList *params, Enviroment *env)
Elem * exportallc (LList *params, Enviroment *env)
Elem * replc (LList *params, Enviroment *env)
Elem * consc (LList *params, Enviroment *env)
Elem * plusc (LList *params, Enviroment *env)
Elem * minusc (LList *params, Enviroment *env)
Elem * multiplyc (LList *params, Enviroment *env)
Elem * divisionc (LList *params, Enviroment *env)
Elem * moduloc (LList *params, Enviroment *env)
bool lequeal (Elem *a, Elem *b)
Elem * equalc (LList *params, Enviroment *env)
Elem * biggerc (LList *params, Enviroment *env)
Elem * smallerc (LList *params, Enviroment *env)
Elem * notc (LList *params, Enviroment *env)
Elem * andc (LList *params, Enviroment *env)
Elem * orc (LList *params, Enviroment *env)
Variables
LBool * True = new LBool(true)
LBool * False = new LBool(false)
Function Documentation
Elem* printc (LList * params, Enviroment * env)
Vytiskne (a evaluuje) všechny své parametry.
Example:
 (print 1 2 (+ 1 1 1))
Definition at line 21 of file stdlibc.h.
References LList::car, LList::cdr, Enviroment::eval(), and Elem::printable().
Referenced by Enviroment::Enviroment().
Elem* setc (LList * params, Enviroment * env)
vezme první parametr - požadovaný název (symbol) a pod tímto názvem uloží evaluovanou hodnotu druhého parametru
Example:
 (set deset (* 2 5))
Definition at line 36 of file stdlibc.h.
References LList::car, LList::cdr, Enviroment::define(), Enviroment::eval(), expect_LSymbol(), LSymbol::name, LFunction::name, Nparams(), and Elem::whois().
Referenced by Enviroment::Enviroment().
Elem* quotec (LList * params, Enviroment * env)
Vezme svůj parametr a vrátí ho bez evaluace. Obdoba '(...) z Common Lispu
Example:
 (print (quote (1 2)))
Definition at line 57 of file stdlibc.h.
References LList::car.
Referenced by Enviroment::Enviroment().
Elem* lambdac (LList * params, Enviroment * env)
Vytvoří anonymní funkci.
Example:
 (print ((lambda (x) (+ x 1)) 1)
Definition at line 66 of file stdlibc.h.
References LList::car, LList::cdr, Elem::col, expect_LList(), Elem::line, and Nparams().
Referenced by Enviroment::Enviroment().
Elem* defmacroc (LList * params, Enviroment * env)
Vytvoří makro. První parametr je název makra, druhý seznam parametrů, třetí tělo.
Example:
 (defmacro foo () (quote (print 2)))
 (foo)
Definition at line 91 of file stdlibc.h.
References LList::car, LList::cdr, Enviroment::define(), expect_LList(), expect_LSymbol(), LSymbol::name, and Nparams().
Referenced by Enviroment::Enviroment().
Elem* listc (LList * params, Enviroment * env)
Vrátí seznam utvořený z evaluovaných parametrů
Example:
 (print (list 1 2 3 (+ 2 2)))
Definition at line 111 of file stdlibc.h.
References LList::add(), LList::car, LList::cdr, and Enviroment::eval().
Referenced by Enviroment::Enviroment().
Elem* backquotec (LList * params, Enviroment * env)
Obdoba `(...) v commonlispu. Plní podobnou funkci jako (quote) akorát elementy které jsou v (comma (..)) se evaluují a elementy v (at (...)) se vloží přímo. Na rozdíl od CL se symboly at a comma nehledají rekurzivně.
Example:
   (set P (list 6 7))
   (print (backquote (1         # neevaluuje
                      (- 2 0)   # neevaluuje
                      3         # neevaluuje
                      (comma (+ 2 2))   # evaluuje
                      5         # neevaluuje
                      (at P)))) # evaluuje + se připojí
vypíše: (1 (- 2 0) 3 4 5 6 7)
Definition at line 158 of file stdlibc.h.
References LList::car, LList::cdr, Enviroment::eval(), expect_LList(), expect_LSymbol(), LList::last(), LSymbol::name, and Elem::whois().
Referenced by Enviroment::Enviroment().
Elem* ifc (LList * params, Enviroment * env)
podmínka IF. Syntaxe (if (podminka) (true-vetev) (false-vetev))
Example:
    (defun velikost (x y)
        (if (== x y)
            (print "jsou stejné")
            (if (> x y)
                (print "prvni je vetsi")
                (print "druhy je vetsi"))))
    (velikost 5 9)
Definition at line 208 of file stdlibc.h.
References LList::car, LList::cdr, Enviroment::eval(), expect_LBool(), and LBool::val.
Referenced by Enviroment::Enviroment().
Elem* evalc (LList * params, Enviroment * env)
Vyhodnotí výraz (předaný jako seznam)
Example:
 (eval  (print "nazdar!"))
Definition at line 223 of file stdlibc.h.
References LList::car, Enviroment::eval(), and Elem::printable().
Referenced by Enviroment::Enviroment().
Elem* evallc (LList * params, Enviroment * env)
Vyhodnotí všecky své parametry. Vhodné na místa kam by se jinak dal napsat jen jeden příkaz (např. tělo (lambda). Vrátí hodnotu posledního příkazu.
Example:
    (evall (print "Hello ")
           (print "World!")
           (print NL))
Definition at line 237 of file stdlibc.h.
References Enviroment::progn().
Referenced by Enviroment::Enviroment().
Elem* prognc (LList * params, Enviroment * env)
Podobný jako evallc, akorát parametr vyhodnocuje 2x takže tam může být i proměná
Definition at line 245 of file stdlibc.h.
References LList::car, Enviroment::eval(), expect_LList(), and Enviroment::progn().
Referenced by Enviroment::Enviroment().
Elem* carc (LList * params, Enviroment * env)
Klasická funkce CAR. Vrátí první prvek seznamu
Example:
    (set baz (list 1 2 3 4))
    (print (cdr baz))
Definition at line 260 of file stdlibc.h.
References LList::car, Enviroment::eval(), and expect_LList().
Referenced by Enviroment::Enviroment().
Elem* cdrc (LList * params, Enviroment * env)
Klasická funkce CDR. Vrátí všechny kromě prvého prvku seznamu
Example:
    (set baz (list 1 2 3 4))
    (print (cdr baz))
Definition at line 271 of file stdlibc.h.
References LList::car, Enviroment::eval(), and expect_LList().
Referenced by Enviroment::Enviroment().
Elem* parsec (LList * params, Enviroment * env)
Vezme program v podobě stringu a rozparsuje ho na lispovský datový typy
Example:
    (set data "(1 1 2 3 5 8 13)")
    (print (parse data))
Definition at line 282 of file stdlibc.h.
References LList::car, Enviroment::eval(), expect_LString(), Parser::parseString(), and LString::repr.
Referenced by Enviroment::Enviroment().
Elem* readfilec (LList * params, Enviroment * env)
Načte obsah souboru do LStringu.
Example:
    (set passwd (readfile "/etc/passwd"))
    (print passwd)
Definition at line 295 of file stdlibc.h.
References LList::car, Enviroment::eval(), expect_LString(), and LString::repr.
Referenced by Enviroment::Enviroment().
Elem* vardumpc (LList * params, Enviroment * env)
Vypíše všecky proměný v aktuálním prostředí
Example:
    (vardump)
Definition at line 320 of file stdlibc.h.
References Enviroment::vardump().
Referenced by Enviroment::Enviroment().
Elem* exportallc (LList * params, Enviroment * env)
Exportuje Všechny místní proměný do nadřazených prostředí. (Pro interní použití v funkci import)
Definition at line 328 of file stdlibc.h.
References Enviroment::define(), Enviroment::parent, and Enviroment::symbols.
Referenced by Enviroment::Enviroment().
Elem* replc (LList * params, Enviroment * env)
Spustí REPL (interaktivní režim) v současném prostředí - vhodné pro debugging
Example:
    (set foo "ORLY?!")
    (repl)
Následně:
(printnl foo)
Definition at line 351 of file stdlibc.h.
References Repl::run().
Referenced by Enviroment::Enviroment().
Elem* consc (LList * params, Enviroment * env)
Sestaví lispovský seznam z svých dvou parametrů.
Example:
   (print (cons (cons 1 "dva") 3))
Definition at line 362 of file stdlibc.h.
References LList::add(), LList::car, LList::cdr, Enviroment::eval(), and LList::len().
Referenced by Enviroment::Enviroment().
Elem* plusc (LList * params, Enviroment * env)
Plus (+).
Example:
(+ 1 2 3)
Definition at line 381 of file stdlibc.h.
References LList::car, LList::cdr, Enviroment::eval(), expect_LInt(), and LInt::repr.
Referenced by Enviroment::Enviroment().
Elem* minusc (LList * params, Enviroment * env)
Minus (-).
Example:
(- 128 64 32 16)
Definition at line 397 of file stdlibc.h.
References LList::car, LList::cdr, Enviroment::eval(), expect_LInt(), LList::len(), and LInt::repr.
Referenced by Enviroment::Enviroment().
Elem* multiplyc (LList * params, Enviroment * env)
Násobení (*)
Definition at line 419 of file stdlibc.h.
References LList::car, LList::cdr, Enviroment::eval(), expect_LInt(), and LInt::repr.
Referenced by Enviroment::Enviroment().
Elem* divisionc (LList * params, Enviroment * env)
Celočíselné dělení (/).
Example:
 (print (/ 1000 10 2))
Definition at line 435 of file stdlibc.h.
References LList::car, LList::cdr, Enviroment::eval(), expect_LInt(), and LInt::repr.
Referenced by Enviroment::Enviroment().
Elem* moduloc (LList * params, Enviroment * env)
Zbytek po celočíselném dělení (%).
Example:
 (print (% 124 10))
vytiskne 4
Definition at line 453 of file stdlibc.h.
References LList::car, LList::cdr, Enviroment::eval(), expect_LInt(), and LInt::repr.
Referenced by Enviroment::Enviroment().
bool lequeal (Elem * a, Elem * b)
Pomocná funkce pro zjišťování jestli se dva prvky rovnají.
Definition at line 473 of file stdlibc.h.
References LList::car, LList::cdr, BaseException::desc, expect_LInt(), expect_LList(), expect_LString(), LList::len(), Elem::line, BaseException::line, LString::repr, LInt::repr, strformat(), and Elem::whois().
Referenced by equalc().
Elem* equalc (LList * params, Enviroment * env)
Porovnávání obsahu několika prvků.
Example:
    (print (== 12 (- 15 3) (* 2 6) (+ 9 3) (/ 24 2) (% 52 20))
vypíše True.
Definition at line 549 of file stdlibc.h.
References LList::car, LList::cdr, Enviroment::eval(), lequeal(), LBool::val, and Elem::whois().
Referenced by Enviroment::Enviroment().
Elem* biggerc (LList * params, Enviroment * env)
Větší než.
Example:
 (> 99 7 6 5 3)
Definition at line 572 of file stdlibc.h.
References LList::car, LList::cdr, Enviroment::eval(), expect_LInt(), LInt::repr, and LBool::val.
Referenced by Enviroment::Enviroment().
Elem* smallerc (LList * params, Enviroment * env)
Menší než.
Example:
 (< 99 7 6 5 3)
Definition at line 596 of file stdlibc.h.
References LList::car, LList::cdr, Enviroment::eval(), expect_LInt(), LInt::repr, and LBool::val.
Referenced by Enviroment::Enviroment().
Elem* notc (LList * params, Enviroment * env)
Not - negace
Example:
    (defun >= (x y)
        (not (< x y)))
Definition at line 624 of file stdlibc.h.
References LList::car, Enviroment::eval(), expect_LBool(), Nparams(), and LBool::val.
Referenced by Enviroment::Enviroment().
Elem* andc (LList * params, Enviroment * env)
AND - logický součin. Provádí zkrácené vyhodnocení.
Example:
    (and True (== 1 0) (print "nic se nevypíše"))
Definition at line 637 of file stdlibc.h.
References LList::car, LList::cdr, Enviroment::eval(), expect_LBool(), and LBool::val.
Referenced by Enviroment::Enviroment().
Elem* orc (LList * params, Enviroment * env)
OR - logický součet. Provádí zkrácené vyhodnocování.
Example:
    (defun xor (x y)
        (or
            (and x (not y))
            (and (not x) y)))
    (print (xor False True))
Definition at line 665 of file stdlibc.h.
References LList::car, LList::cdr, Enviroment::eval(), expect_LBool(), and LBool::val.
Referenced by Enviroment::Enviroment().
Variable Documentation
LBool* True = new LBool(true)
Definition at line 13 of file stdlibc.h.
LBool* False = new LBool(false)
Definition at line 14 of file stdlibc.h.